#################################################
#                MasterCTW V1.1                 #
#                Made by Tqmass                 #
#             Collaborator: NoWacho             #
#################################################

# ~ Main Settings

LANG-FILE: languages/english.yml
DATABASE-MODE: MYSQL
SERVER-MODE: INDIVIDUAL
HUB-CORE-ENABLED: true

# ~ DataBase Settings

MYSQL:
  DATABASE_NAME: 'CTW_DB'
  USERNAME: 'root'
  PASSWORD: ''
  ADDRESS: 127.0.0.1
  PORT: 3306
  SSL: false

  STATS_TABLE_NAME: 'ctw_stats'
  MULTIPLIERS_TABLE_NAME: 'ctw_multipliers'
  KIT_EDITOR_TABLE_NAME: 'ctw_kiteditor'

SQLITE:
  DATABASE_FILE: "MasterCTW.db"
  STATS_TABLE_NAME: 'CTW_STATS'
  MULTIPLIERS_TABLE_NAME: 'CTW_MULTIPLIERS'
  KIT_EDITOR_TABLE_NAME: 'CTW_KITEDITOR'

# ~ Server Features

LOBBY-FEATURES:
  TABLIST_ENABLED: true
  HEALTH_DISPLAY: false
  SCOREBOARD_ENABLED: true
  NAMETAGS_ENABLED: true

  STAFF_JOIN_MESSAGE_ENABLED: false
  STAFF_LEAVE_MESSAGE_ENABLED: false
  DONATOR_JOIN_MESSAGE_ENABLED: true
  DONATOR_LEAVE_MESSAGE_ENABLED: false

  JOIN_TITLE_ENABLED: false
  ACTION_BAR_MESSAGES: false

GAME-FEATURES:
  TABLIST_ENABLED: true
  HEALTH_DISPLAY: true
  SCOREBOARD_ENABLED: true
  NAMETAGS_ENABLED: true

  SHUFFLE_MAPS: false
  REQUIRE_PLAYERS_START: false
  PLAYERS_REQUIRED_START: 3 #Requires REQUIRE_PLAYERS_START enabled.

  TITLES_ENABLED: true
  ACTION_BAR_ENABLED: true

  KILLSTREAK_ENABLED: true
  BOUNTY_ENABLED: true
  CUSTOM_ACHIEVEMENTS: true
  DONATOR_TRAILS_ENABLED: false

  STAFF_JOIN_MESSAGE_ENABLED: false
  STAFF_LEAVE_MESSAGE_ENABLED: false
  DONATOR_JOIN_MESSAGE_ENABLED: true
  DONATOR_LEAVE_MESSAGE_ENABLED: false

# ~ Lobby Core Settings

HUB-CORE-SETTINGS:
  VOID_TELEPORT: true
  EXPLOSIONS: false
  FIRESPREAD: false
  VEHICLE_USE: false
  FALL_DAMAGE: false
  LOSE_HUNGER: false
  TIME_CHANGE: false
  WEATHER_CHANGE: false
  DECAY_GROWTH: false
  BLOCK_MELT_FORM: false
  BREAK_MAP: false
  PLACE_BLOCKS: false
  ITEM_PICKUP: false
  ITEM_DROP: false
  CRAFT_ITEMS: false
  PLAYER_DAMAGE: false
  PLAYER_INTERACT: false
  INVENTORY_INTERACT: false
  MOBS_SPAWN: false
  MOBS_ATTACK: false

# ~ Game Core Settings

GAME-CORE-SETTINGS:
  VOID_INSTAKILL: true
  AUTO_RESPAWN: true
  WOOL_RADIO: true
  BLOCK_REGEN: true
  FALL_DAMAGE: true
  ENEMY_BASE_ACCESS: false
  LOSE_HUNGER: false
  EXPLOSIONS: true
  FIRESPREAD: false
  CRAFT_ITEMS: true
  TIME_CHANGE: false
  WEATHER_CHANGE: false
  DECAY_GROWTH: false
  BLOCK_MELT_FORM: false
  VEHICLE_USE: true
  PORTALS_ENABLED: false

# ~ Join/Leave Messages Settings

JOIN-LEAVE-MESSAGES:
  SPIGOT-JOIN-MESSAGE:
    SPIGOT_ENABLED: false
    CUSTOM_ENABLED: false
    ENABLE_SOUND: false
    SOUND: "LEVEL_UP"
  SPIGOT-LEAVE-MESSAGE:
    SPIGOT_ENABLED: false
    CUSTOM_ENABLED: false
    ENABLE_SOUND: false
    SOUND: "NOTE_PLING"

  DONATOR-JOIN-MESSAGE:
    PERMISSION: "masterctw.donator.joinmsg"
    ENABLE_SOUND: false
    SOUND: "LEVEL_UP"
  DONATOR-LEAVE-MESSAGE:
    PERMISSION: "masterctw.donator.leavemsg"
    ENABLE_SOUND: false
    SOUND: "NOTE_PLING"

  STAFF-JOIN-MESSAGE:
    PERMISSION: "masterctw.staff.joinmsg"
    ENABLE_SOUND: false
    SOUND: "LEVEL_UP"
  STAFF-LEAVE-MESSAGE:
    PERMISSION: "masterctw.staff.leavemsg"
    ENABLE_SOUND: false
    SOUND: "NOTE_PLING"

# ~ Lobby Servers List
# Configure this in case you are using BungeeCord Mode.

LOBBY-SERVERS-LIST:
  - LobbyCTW1
  - LobbyCTW2
  - LobbyCTW3

# ~ Map Cycle | Map order List

MAP-GAME-CYCLE:
  - Map1
  - Map2
  - Map3

# ~ Rewards Settings
# Put 0 for disable

REWARDS:
  POINTS:
    WIN: 20
    LOSE: 0
    KILL: 1
    ASSIST: 1
    DEFENSE: 3
    DEATH: -1
    PICKUP_WOOL: 5
    PLACE_WOOL: 5
    DOUBLE_WOOL_CAPTURE: 10
  GLOBAL_COINS:
    WIN: 10
    LOSE: 0
    KILL: 3
    ASSIST: 1
    DEFENSE: 3
    DEATH: 0
    PICKUP_WOOL: 10
    PLACE_WOOL: 20
    DOUBLE_WOOL_CAPTURE: 30
  GAME_COINS:
    WIN: 20
    LOSE: 0
    KILL: 5
    ASSIST: 3
    DEFENSE: 8
    DEATH: 0
    PICKUP_WOOL: 20
    PLACE_WOOL: 30
    DOUBLE_WOOL_CAPTURE: 50

# ~ Custom Achievement Settings
CUSTOM_ACHIEVEMENTS:
  SNIPER:
    DISTANCE_REQUIRED_I: 25
    DISTANCE_REQUIRED_II: 35
    DISTANCE_REQUIRED_III: 45
    DISTANCE_REQUIRED_IV: 55
    DISTANCE_REQUIRED_V: 65
  KILLER:
    KILLS_REQUIRED_I: 50
    KILLS_REQUIRED_II: 100
    KILLS_REQUIRED_III: 150
    KILLS_REQUIRED_IV: 200
    KILLS_REQUIRED_V: 250
  BOW-FIGHTER:
    KILLS_REQUIRED_I: 50
    KILLS_REQUIRED_II: 100
    KILLS_REQUIRED_III: 150
    KILLS_REQUIRED_IV: 200
    KILLS_REQUIRED_V: 250
  OVERPOWERED:
    KILLS_REQUIRED_I: 120
    KILLS_REQUIRED_II: 250
    KILLS_REQUIRED_III: 500
    KILLS_REQUIRED_IV: 1000
    KILLS_REQUIRED_V: 1500
  SUPPORTER:
    ASSISTS_REQUIRED_I: 50
    ASSISTS_REQUIRED_II: 100
    ASSISTS_REQUIRED_III: 150
    ASSISTS_REQUIRED_IV: 200
    ASSISTS_REQUIRED_V: 250
  GUARDIAN:
    KILLS_REQUIRED_I: 50
    KILLS_REQUIRED_II: 100
    KILLS_REQUIRED_III: 150
    KILLS_REQUIRED_IV: 200
    KILLS_REQUIRED_V: 250
  WOOL-MASTER:
    WOOLS_REQUIRED_I: 25
    WOOLS_REQUIRED_II: 50
    WOOLS_REQUIRED_III: 100
    WOOLS_REQUIRED_IV: 200
    WOOLS_REQUIRED_V: 500
  WINNER:
    WINS_REQUIRED_I: 15
    WINS_REQUIRED_II: 50
    WINS_REQUIRED_III: 100
    WINS_REQUIRED_IV: 200
    WINS_REQUIRED_V: 500
  EXPERIENCED:
    GAMES_REQUIRED_I: 50
    GAMES_REQUIRED_II: 100
    GAMES_REQUIRED_III: 150
    GAMES_REQUIRED_IV: 200
    GAMES_REQUIRED_V: 250
